### PR TITLE
Pr 92 - rev 2

### PR DESCRIPTION
**Pull request by BarbourSmith**
Building on @johnbenweber work in #92 . Added back in the position indicator shown while fast forwarding and fixing an index error so that the % complete ends at 100%.

@blurfl Do you think it's clear enough that the user is at the begning or end of the file? We could disable (turn grey) the buttons to FF or rewind if the user is at the begining or end of the file to make it more clear.

### CODE REVIEW

**Comment by johnbenweber** [comment]
I probably should have looked at this before commenting on the other PR.

@blurfl I agree about the behavior of the line number and percentage. We just need to call self.moveGcodeIndex(0) when a new file is loaded.

**Comment by BarbourSmith** [comment]
Great catch @blurfl !

I added a call to moveGocdeIndex which resets it. 

There are still ways to make the system better like holding buttons to FF and disabling the buttons when you are at the edges of the file, but I think this is still much better than it was this morning. 

Any objections to merging this PR as it is and then improving things further in a new PR later?

On a personal note, this is WAY more fun with other people than when I'm the only one looking at this. Thank you two for being involved!

**Comment by blurfl** [comment]
You guys are hot! By all means merge it. 
 Off topic, but any chance of bringing the OSX branch up to date?

**Comment by johnbenweber** [comment]
@BarbourSmith and @blurfl agreed, looks good guys.

**Comment by BarbourSmith** [comment]
Great!

I just brought my build-OSX branch up to date, so it should be good to go.

Is everything still compiling OK?

**Comment by blurfl** [comment]
It compiles 👍, but two issues have surfaced 😔. I’ll open them in that branch, yes?

**Pull request merged**
