### PR TITLE
Ignore decimal places in gotoLine popup, enable keyboard input for NotificationPopup and TouchNumberInput popups

### PR DESCRIPTION
**Pull request by wrh3c**
Please review my two commits for possible inclusion in GroundControl.

### CODE REVIEW

**Comment by blurfl** [comment]
This makes sense. Which platform has it been tried on? I can test OS X and/or Win10, if needed.

**Comment by BarbourSmith** [comment]
@blurfl I'm about to test windows 10, if you could do OS X and give us your feedback that would be awesome!

**Comment by BarbourSmith** [comment]
Checks out GREAT on windows. Thanks @wrh3c  for taking the time to make sure the callbacks for the canvas zoom don't break with the new popup feature. It feels really natural to me to type in the values like this, and I really like that the enter key closes the popup and applies the value.

Excellent contribution. Thank you! 👍 👍 ❤️ ❤️

**Comment by blurfl** [comment]
Will do. I’m on a ladder, get it in 45 minutes.

**Comment by BarbourSmith** [comment]
@blurfl  be safe up there, we need you 😁

**Comment by blurfl** [comment]
Works fine on OS X, a very good improvement. 💯 
 'on a ladder'... I should have said "I've gotta climb back up and finish before sitting down to a keyboard."

**Pull request merged**
