### PR TITLE
Fix for issue #171

### PR DESCRIPTION
**Pull request by BarbourSmith**
Gcode now reloads to the same location as it was before and the line number is preserved when reloading gcode. See issue #171

### CODE REVIEW

**Comment by BarbourSmith** [comment]
Not quite ready to merge. Two outstanding issues. 1) When you cut it the gcode hasn't actually been moved 2) Something is still blocking when clicking the Define Origin button

**Comment by BarbourSmith** [comment]
I think it's all working the way I would like it to.

@blsteinhauer88 , when you get a chance will you take a look at this and see if there are any tweaks you would like to see before I merge it?

**Comment by blsteinhauer88** [comment]
If you say it's good, lets go for it, I can't read code. Lol

**Comment by BarbourSmith** [comment]
Sorry, it was a confusing question. There's a way to download it and test it, but I should have just merged it and then asked if master looked good.

**Comment by blsteinhauer88** [comment]
Gotcha, I just loaded the update yesterday, when I get home tonight I have
a project to cut and will use the Master Groundcontrol to do it.  Thanks.
Lon

**Pull request merged**
