### PR TITLE
Add a close button to chain calibration

### PR DESCRIPTION
**Pull request by skiz**
Add close button to calibration first step.

### CODE REVIEW

**Comment by skiz** [comment]
fixes #454

**Comment by blurfl** [comment]
This would be by way of cancelling the calibration, right? Would 'Cancel' be more appropriate than 'Close'?

**Comment by skiz** [comment]
@blurfl The only 'Cancel' in the app is in the save dialog, all popups use 'Close', so just following the existing design.

**Comment by blurfl** [comment]
Some of these dialogs put the machine into relative mode, let's make sure that exiting this way restores the machine to the condition it was in before it entered the page.

**Comment by BarbourSmith** [comment]
I like it!

@blurfl is right that we have to be careful of the machine's state when exiting the calibration routine at weird points because once the "Begin" button is pressed things like relative mode, mm mode, and the chain lengths can be left in strange states. I feel good about the close button here in the first step because it is accessible before clicking the begin button. Using the back button to get back there then closing could be an issue, but that's already possible when fast forwarding to the end

**Comment by blurfl** [comment]
"...Using the back button to get back there then closing could be an issue, but that's already possible when fast forwarding to the end" This is probably how I get bitten, trying to use parts of the process. Do we need an issue to capture this?

**Comment by BarbourSmith** [comment]
Yes! Great suggestion @blurfl 

I will merge this as is and let's make a new issue for "it's not clear that exiting the calibration process part way through can cause trouble"

**Pull request merged**
