### PR TITLE
Pull Request to Merge Holey Calibration into MaslowCNC:main fork

### PR DESCRIPTION
**Pull request by schmittjoshc**
All changes from schmitjoshc/GroundControl:main being merged into MaslowCNC/GroundControl:main

### CODE REVIEW

**Comment by blurfl** [comment]
While this is a development that is much anticipated, maybe a PR that makes so many changes should wait until after the pending release. That would separate these changes from others and make testing and rollback easier.

**Comment by blurfl** [comment]
Closing this manually as the CommunityGarden robot for this repo seems to be on hiatus.

**Comment by ted1735** [comment]
This looks amazing I want this.. Did it merge through

**Comment by davidelang** [comment]
no, we decided to hold off until after we make a release that includes all the 
other changes since January, then we will merge this for testing

David Lang

**Comment by BarbourSmith** [comment]
The people who are selling kits are testing the current release on their machines, if they say the release is OK then I will make a release and then we can reopen this pull request (which is awesome!)

Give it a 👍 vote and when it reopens it should merge automatically (although the robot needs some love soon)

**Comment by davidelang** [comment]
now that we have more than just you testing, can we set a schedule for testers? 
something like: take whatever is current at the 1st of the month and if nobody 
gives it a no vote by the 7th, it ships?

do this on odd-numbered months (which avoids Jan 1 and July 4 interrupting 
testing)?

I like a 'default ship' as that means that if someone drops out of testing or 
becomes unresponsive it can't block the release forever.

David Lang

**Pull request closed without merging**
