### PR TITLE
Add advanced settings options to set PID values for Z

### PR DESCRIPTION
**Pull request by BarbourSmith**
Adds a settings panel to add options to tune the PID values for the z-axis as requested in this forum thread:

https://forums.maslowcnc.com/t/how-to-make-permanent-changes-to-z-axis-kp-ki-kd/5106/14

image

### CODE REVIEW

**Comment by Domidovr** [comment]
Hi,
I need it for my custom Z Axis which require different settings...
There are 8 settings 4 for the position PID and 4 for the velocity PID
thanks
Dominique

**Comment by blurfl** [comment]
There are at least two serious issues with this in the present form. It would be a good idea to make a backup copy of groundcontrol.ini before going on.

To see the first issue - use Actions/Advanced/ResetSettingsToDefaults to remove groundcontrol.ini as it is supposed to, or move the file so it will be re-created. GC will open without a port selected and as soon as a port is connected, GC will crash with this error:
```
ConfigParser.NoOptionError: No option 'propweightz' in section: 'Computed Settings'
````
Haven't looked more deeply into this behavior.

The second issue is that though the Advanced options page presents and allows editing of the z axis Kp and Kv values, those values never seem to become effective as determined by watching the output of the '$$' command which lists the values in EEPROM. I'm using this to watch the command line for the pertinent responses from the firmware to GC:

```
rm log.txt  ; touch log.txt ; tail -f log.txt | egrep -v '([[<].*|ok)'

```
 Leaving the 'enablepospidvalues' or 'enablevpidvalues' settings off in the Advanced page, change some of the values using these gcodes:
```
Sent: $29=998   
Sent: $30=666   
Sent: $31=333   
Sent: $$ 
$0=2438.40 (machine width, mm)
$1=1219.19995117 (machine height, mm)
$2=2978.39990234 (motor distance, mm)
$3=463.00000000 (motor height, mm)
$4=310.00000000 (sled width, mm)
$5=139.00000000 (sled height, mm)
$6=79.00000000 (sled cg, mm)
$7=2 (Kinematics Type 1=Quadrilateral, 2=Triangular)
$8=100.00000000 (rotation radius, mm)
$9=2000 (axis idle before detach, ms)
$10=3360 (full length of chain, mm)
$11=1650 (calibration chain length, mm)
$12=8113.73046875 (main steps per revolution)
$13=63.50000000 (distance / rotation, mm)
$15=800 (max feed, mm/min)
$16=1 (Auto Z Axis, 1 = Yes)
$17=0 (auto spindle enable 1=servo, 2=relay_h, 3=relay_l)
$18=12.60000038 (max z axis RPM)
$19=55.78000259 (z axis distance / rotation)
$20=33600.00000000 (z axis steps per revolution)
$21=1300.00000000 (main Kp Pos)
$22=0.00000000 (main Ki Pos)
$23=34.00000000 (main Kd Pos)
$24=1.00000000 (main Pos proportional weight)
$25=5.00000000 (main Kp Velocity)
$26=0.00000000 (main Ki Velocity)
$27=0.28000001 (main Kd Velocity)
$28=1.00000000 (main Velocity proportional weight)
$29=998.00000000 (z axis Kp Pos)
$30=666.00000000 (z axis Ki Pos)
$31=333.00000000 (z axis Kd Pos)
$32=1.00000000 (z axis Pos proportional weight)
$33=5.00000000 (z axis Kp Velocity)
$34=0.00000000 (z axis Ki Velocity)
$35=0.28000001 (z axis Kd Velocity)
$36=1.00000000 (z axis Velocity proportional weight)
$37=0.00000000 (chain sag correction value)
$38=1 (chain over sprocket)
$39=1 (PWM frequency value 1=39,000Hz, 2=4,100Hz, 3=490Hz)
$40=63.50000000 (distance / rotation, including chain tolerance, left chain, mm)
$41=63.50000000 (distance / rotation, including chain tolerance, right chain, mm)
$42=5.00000000 (position error alarm limit, mm)
Sent: $29=1300 
Sent: $30=0 
Sent: $31=34 
```
In the above, see the values for $29, $30 and $31 sent, and reflected when '$$' queries the present values, but immediately after that the three values are overwritten. Not certain where the values used for overwriting originate...

The third issue is that the values for k_posz and k_vz in groundcontrol.ini::[Computed Settings] become wrong when the 'enablepospidvalues' or 'enablevpidvalues' settings are changed to 'ON', and only restoring a version of groundcontrol.ini with valid values corrects this.

**Comment by BarbourSmith** [comment]
What a mess! Thank you for catching the multitude of issues here 😬 

I'm going to close this pull request for right now and start digging into those

**Comment by BarbourSmith** [comment]
I think I've got all the bugs fixed. I will open a new pull request on Monday

**Pull request closed without merging**
