### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by davidelang**
minor tweaks to the simulation

plot the grid within the window (not centered as I don't know how to find the window width)
change the grid to 6" squares rather than the odd measurements that existed before.

### CODE REVIEW

**Comment by davidelang** [comment]
added changes to the kv display to include a slider for CG error and display the machine dimensions.

**Comment by davidelang** [comment]
I'm not sure why it is complaining about a conflict, I'm adding some lines where it is unhappy.

I completely re-worked this set of changes to split them up into different commits and clean them up

**Comment by davidelang** [comment]
added 2x speedup commit

**Comment by davidelang** [comment]
reading the merge commit, it looks like I had another thing that snuck in without me realizing it, tinkering with the scale size, check that if it comes out too large on your systems.

**Comment by BarbourSmith** [comment]
In general these all seem like beneficial changes. I agree that we can cherry pick out the commit which moved it to the center because it's not necessary anymore, but overall awesome contributions!

**Pull request merged**
