### PR TITLE
Temp fix for issue #300 

### PR DESCRIPTION
**Pull request by BarbourSmith**
Wait until one line has finished processing before sending the next. Slow, but doesn't result in loss of data

### CODE REVIEW

**Comment by BarbourSmith** [comment]
This is basically reverting back to how things were in 0.71. It's notably slower, but at least it gives us a stable point to work from until we find a better solution.

@blurfl Will you verify that this fixes the issue for you also?

**Comment by blurfl** [comment]
Same branch?

**Comment by blurfl** [comment]
GitHub service outage, will try again in a bit...

**Comment by BarbourSmith** [comment]
I know, right?

Git hub being down is a big deal. They had some struggles yesterday too.

**Comment by davidelang** [comment]
If you have hosting available, git repositories can be replicated, and there is 
nothing technical that makes one the master and the other the slave (just which 
one you push to first)

hopefully github will figure out what's going on here quickly, I haven't seen 
anything reported about them having problems, which surprises me a bit.

**Comment by BarbourSmith** [comment]
Oops, targeted the wrong branch 😬

**Comment by blurfl** [comment]
Is there a way I can help?

**Comment by BarbourSmith** [comment]
I've just got to resolve some conflicts and make a new pull request.

Will you test it again once I do to make sure I haven't broken it in the process?

**Comment by blurfl** [comment]
Sure! Standing by 😊👍

**Comment by BarbourSmith** [comment]
Thanks! Give #315 a test when you have a chance.

I'm testing it again right now too.

**Comment by blurfl** [comment]
When I run this, it prompts for the z-axis.

**Comment by BarbourSmith** [comment]
Hmm, do you still see missing lines, or just the z-axis prompting?

**Comment by BarbourSmith** [comment]
Prompting for the z-axis makes me think that the machine settings aren't being received by the machine right

**Comment by blurfl** [comment]
No missing lines.

When I edit line 23 of serialPortThread.py as so:
        message = message + '\n'#'L' + str(len(message) + 1 + 2 + len(str(len(message))) ) + " \n"

The z axis works as expected.

**Comment by BarbourSmith** [comment]
Fantastic!

What was the change to that line? I'm not spotting the difference 😀

**Comment by blurfl** [comment]
I changed  “ \n”. That is double quote space backslash n double quote to single quote backslash n single quote

I know very little python, this is one of the "witch-doctor’s chicken bones" I wave at a problem. Here, it made a difference :)

**Comment by BarbourSmith** [comment]
Ahhhhh! Thanks! My mind just saw quotes. I'm making the change now.

Thank you for testing that.

**Comment by davidelang** [comment]
That calculation (that you are commenting out) is wrong

if the +3 causes the calculation to wrap to an additional digit, this will end 
up using more space in the queue than the L parameter says.


"(23456)" would become
"(23456)L11 \n" which is 12 bytes

**Comment by BarbourSmith** [comment]
It seemed to work because we've been using it all day, but I'll keep take a look at it. Maybe something I don't understand is happening

**Comment by blurfl** [comment]
Ok, I just downloaded the version with single quotes that you just did and saw the z-axis issue again.
 You mentioned machine settings, so I looked and saw the z-axis switch looked correct. I went back and poked ‘Home’ and the sled moved instead of the z axis. I went back to settings and switched z-axis off and on again, then ‘Home’ worked correctly.

**Comment by davidelang** [comment]
slowing down transmissions so that the arduino can process more data makes it 
less likely to fill the circular queue if you are sending mostly 
quick-to-execute commands, so that will make it seem like it's working. But if 
you were to transmit commands that take longer to execute (large moves back and 
forth), then you will still fill up the queue and run into the problem

for example, I'll bet that something like the following will still give you 
grief (lots of commands that take a lot of time to execute)

G21 G90 G40
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000
G1 X-1140.0000000 Y-480.000000 Z0.0000000 F6.000000
G1 X1140.0000000 Y480.000000 Z0.0000000 F6.000000

**Comment by blurfl** [comment]
I’ll run your torture test, but F6.000000 is too slow. I’m going to up it to F600.0000

**Comment by blurfl** [comment]
I’m thinking you didn’t intend this to be tested against the version that Bar is releasing this week. Too, how about a version that doesn’t travel to the ends of the earth; that isn’t necessary to this test, but sure takes a lot of time and means the whole work area needs to be cleared :)

**Comment by blurfl** [comment]
Also, GroundControl seems pretty savvy about truncating zeros, the lines come across as (after I shortened the travel and upped the speed:

G1 X-140.0 Y-80.0 Z0.0000000 F6000.000   
G1 X140.0 Y80.0 Z0.0000000 F6000.000   
G1 X-140.0 Y-80.0 Z0.0000000 F6000.000   
G1 X140.0 Y80.0 Z0.0000000 F6000.000   
G1 X-140.0 Y-80.0 Z0.0000000 F6000.000   
G1 X140.0 Y80.0 Z0.0000000 F6000.000

**Comment by blurfl** [comment]
Bar, I just downloaded and ran the master after PR#315. The machine settings aren’t correctly loaded so when ‘Home’ is pressed the sled moves. A work-around is to switch the z-axis setting off then back on. The complex cut ran without error :) .

**Comment by davidelang** [comment]
The purpose was to have this take lots of time, so that the firmware would not 
be clearing the buffer, even with the delays in sending.

That's why the large, slow movements.

This is intended to be run against the version that still sends multiple 
messages, not the slower-but-reliable version where only one command at a time 
is pending.
k

**Comment by blurfl** [comment]
How much time should it take to fill a 256 byte buffer at 57600 baud? Traveling 2400 mm at 6mm per minute for each line of gcode does seem extreme. :)

**Pull request merged**
