### PR TITLE
Images to support KivyPi Mouse Positioning

### PR DESCRIPTION
**Pull request by TheRiflesSpiral**

### CODE REVIEW

**Comment by TheRiflesSpiral** [comment]
This should work. I'll update the instructions after the commit.

**Comment by TheRiflesSpiral** [comment]
Sorry, wrong button.

**Comment by BarbourSmith** [comment]
This looks perfect and normal from my end 👍 👍 👍

**Comment by BarbourSmith** [comment]
Fantastic!

**Comment by TheRiflesSpiral** [comment]
Fantastic!

**Pull request merged**
