### PR TITLE
Added regular expression substitution to truncate long floats.

### PR DESCRIPTION
**Pull request by johnbenweber**
Truncate digits more than 4 from the decimal place. See Issue #310.

### CODE REVIEW

**Comment by blurfl** [comment]
Thank you, John - that’s exactly what I had in mind! Would it be useful to have this be a checkbox option, or to have the number of digits changeable, maybe on the advanced settings page? For me, 4 digits seems right but others might have different thoughts.

**Comment by davidelang** [comment]
4 digits is probably right if you are in inch mode, but drastic overkill if you 
are in mm mode.
kk

**Comment by blurfl** [comment]
Would we need separate settings for each mode? Would the program need to identify which system the file used, so to choose the appropriate value or would the user be responsible to maintain the corrrect setting for the file in current use? That’s all getting pretty complicated. 
I think just leaving it like this, truncating (not rounding) at four digits is the way to go.

**Comment by johnbenweber** [comment]
We could add a setting for number of decimal places. I think 4 places is probably overkill for both modes. I vaguely remember @BarbourSmith saying that accuracy was ~0.5mm or ~0.020in meaning we would really be alright in both cases with 2 decimal places. I'm not sure how valuable saving characters is so it's hard to say if further complication is justified.

**Comment by blurfl** [comment]
You’re right about the accuracy, two digits probably is close enough. Being able to set the digits or at least enable/disable the truncation would be nice, though.
Buffering the serial data is an ongoing issue, so saving characters might be helpful as a bandaid.

**Comment by johnbenweber** [comment]
If I have time I can work on adding relevant options (enable/disable and digits).

**Comment by johnbenweber** [comment]
Give it a try now. I think the problem was specifying a python boolean "True" for the default value when kivy was expecting a 1 or 0.

**Comment by blurfl** [comment]
That's the bunny! Now it is perfect. 💯 👍 🥇

**Comment by BarbourSmith** [comment]
Excellent addition and great community review! 

Great work everyone 👍 👍 👍

**Pull request merged**
