### PR TITLE
Update the command to wipe the EEPROM

### LINKED ISSUE #532: B07 (Wipe Eeprom) results in -> error: Invalid gcode ID:78
OS: Linux
FW: 1.02
GC:1.02

->Actions -> Advanced -> Wipe EEPROM
Result in GC=
B07
error: Invalid gcode ID:78

### PR DESCRIPTION
**Pull request by BarbourSmith**
Updates to use the new command to wipe the EEPROM. This uses the maximum option of wiping the entire 4k EEPROM

Fixes #532

### CODE REVIEW

**Comment by krkeegan** [comment]
Looks good.  Do we want to also push the settings currently stored in GC?  Otherwise the user is left in a state where the firmware has different settings than what the user sees in GC.  This rectifies itself on a restart.

**Comment by BarbourSmith** [comment]
Great point! I will add a trigger to push the settings after a wipe. Thanks for catching that 👍 👍

**Comment by BarbourSmith** [comment]
Wiping the full 4k of memory takes long enough that the connection drops and then comes back like this:

image

(ignore the pcb version not being detected, I'm running a cut and testing on an arduino without a shield)

**Comment by BarbourSmith** [comment]
I added a 6 second delay before the settings are pushed to ensure that the eeprom is fully wiped. I think the process is always going to be a little cluttered with at least one prompt to re-calibrate popping up, but I that's OK wiping the EEPROM completely does require a recalibration at least.

I really like the warning that the EEPROM could not be read and the default settings are being used @krkeegan . Nice design.

**Pull request merged**
