### PR TITLE
Adjust KpV Value to Fix Choppy Movement Issue

### PR DESCRIPTION
**Pull request by krkeegan**
Should fix most if not all of the choppiness seen by some users.

### CODE REVIEW

**Comment by blurfl** [comment]
It does make a noticeable difference. 👍

**Comment by BarbourSmith** [comment]
Beautiful! I'm really glad we got this into 1.03, I think a lot of people will appreciate it

Thanks for testing @blurfl I don't see the issue so I can't test ☹️

**Comment by davidelang** [comment]
could you add some comments to these places, giving a rough idea of how to 
experiment with these values (links to online explinations are a good start)

David Lang

**Comment by krkeegan** [comment]
I spent a lot of time putting this together a while ago:

https://github.com/MaslowCNC/Firmware/wiki/PID-Tuning

But honestly, a lot of this is just trial and error.

**Comment by davidelang** [comment]
please put a link to that page next to the parameters in the code.

David Lang

**Pull request merged**
