### PR TITLE
Switch to measuring dist between motors

### PR DESCRIPTION
**Pull request by BarbourSmith**
Switch to measuring the distance between the motors in settings instead of the motor offset distance. 

The distance between the motors is easier to measure and makes more sense to reduce the chance of confusion.

This pull request needs to be merged at the same time as a similar pull request in firmware

### CODE REVIEW

**Comment by johnbenweber** [comment]
I'm not sure how the kinematics works now but there used to be a constant for the diameter of the gear on the motor in the firmware. My gears are a different size than the stock ones so it would be nice if I didn't have to change the firmware. Same for encoder steps per revolution. Perhaps there could be an advanced section in the ground control settiings?

**Comment by davidelang** [comment]
If there is a constant/variable for the diameter of the gear, it should be 
changed to the number of teeth in the gear and the link size. People can easily 
count the number of teeth, and from that and the link size, the diameter can 
easily be calculated. But getting someone to properly measure the diameter of a 
gear is hard, and a small error in the diameter will translate to a large error 
later on.

**Comment by davidelang** [comment]
also see #73 and #127 This should be measured, but not by the builder, it should be measured by the machine

**Comment by johnbenweber** [comment]
I agree that the number of teeth and chain pitch is an easy way to work out the pitch diameter of the gear. I've seen the algorithm for determining distance between the motor centers but I think number of gear teeth/chain pitch is something you'll have to input if you have a non-standard setup. I'm not sure how the machine would work that one out without some sort of limit switch setup which I feel adds unnecessary complication. Looks like advanced settings is my next project.

**Comment by BarbourSmith** [comment]
👍 👍 👍 

@davidelang I agree 100% that we really want the machine to be measuring itself. This PR is one step in that direction (ie using the distance between the motors which the machine will measure itself instead of some arbitrary point (the corner of the plywood) which would be hard to reference). Your comments in #127 are spot on.

@johnbenweber You are looking for line 45 in CNC_Functions.h which is 

```python
#define DIST_PER_ROTATION 10*6.35//#teeth*pitch of chain
```

How's everything going with the build? Anything we can do to help?

**Pull request merged**
