### PR TITLE
Zero z 595

### PR DESCRIPTION
**Pull request by thormj**
Fixes Issue  #595  and adds "ZeroZ Touch" and e-stop to the Z-calibration carousel

### CODE REVIEW

**Comment by blurfl** [comment]
Although I use the touch plate frequently, I don't think it belongs in the standard cal sequence. It requires extra equipment (which is shamefully poorly documented 😳) and isn't widely used. 
My approach is to define one of my macros for this purpose (wish there were more macros available...) I also have a single-purpose .nc file to load which does only this thing. 
Now that the workarea accuracy is better near the edges, I've been thinking of putting a grounded screw head flush way up in a corner, out of the way of cuts. Still need to attach the clip to the bit, though.

If others want to persue this, it will need some very good pictures and description on the page.

**Comment by BarbourSmith** [comment]
I agree with your concerns @blurfl, I also think that @thormj is onto something important which is that we need to make it more clear to people that the z-axis touch probe is an option.

I think we have a little bit of a chicken and the egg problem where nobody uses it, because the feature isn't that well documented, and it's not that well documented because nobody uses it.

How would we feel about adding it to this z-axis popup instead:

image

I am going to tidy up the calibration process very soon (as soon as the frame is all squared 😉 away), and one of the changes I want to make is to use the regular z-axis popup in that step where you move the z-axis up and down.

**Comment by thormj** [comment]
I might've been possessed by creeping featurism when I added the "z-touch"... for people with a flush touch area, they'll probably need to move to the spot and then bring up the Z menu, and it isn't really needed in the machine setup dialogs (except for "Do I have a powered Z"), though I do like the idea of "if you make it through this, you'll know your machine is setup properly and is functional"

**Comment by thormj** [comment]
Ooh... Eye have an apostrophe - how about we change this so the screen has an "enable z-touch" switch on it that puts/removes a z-touch button on the popup menu?  Probably replace the picture  with 2 pics (one of powered z and one that shows the wiring/pic of the z-touch feature, and add some text saying "if you have a z-touch, you probably want to move to the correct position and the use the Z button instead of calibrating it here"

**Comment by blurfl** [comment]
> tidy up the calibration process very soon

While you're in there how about arranging the separate 'Automatic Chain Cal...' screen to allow exiting when the sprockets are aligned? Currently there is no clean way out of 'Automatic Chain Cal...'. That or make the sprocket alignment available to the manual chain cal screen. I think that if the chain management arrangement goes horizontal the manual cal will become more important.

**Comment by BarbourSmith** [comment]
@thormj See what I've done in #604 

How does it fit with what you are saying?

**Comment by thormj** [comment]
Taking @BarbourSmith's commit and running with it instead

**Pull request closed without merging**
