### PR TITLE
Beam tilt correction

### PR DESCRIPTION
**Pull request by johnboiles**
I'm starting to cherry-pick features and fixes from @madgrizzle's fork so that we can get them merged back upstream.

This change is the GroundControl change for beam tilt correction (added to the firmware in MaslowCNC/Firmware#467)

(this is a duplicate of #778 since that one can't be re-opened because of a force push)

### CODE REVIEW

**Comment by johnboiles** [comment]
Forum discussion in this post: https://forums.maslowcnc.com/t/top-beam-tilt-correction-pull-request/7307

**Comment by davidelang** [comment]
for reasons I discussed earlier, no for the reasons mentioned earlier, I want to vote no, but don't seem to have the ability to do so right now

**Comment by BarbourSmith** [comment]
@davidelang to vote you have to do the 👍  or 👎  on the @MaslowCommunityGardenRobot comment. I know that's tough because you mostly read by email, but I am note sure of another solution

**Comment by davidelang** [comment]
On Wed, 17 Oct 2018, BarbourSmith wrote:

> @davidelang to vote you have to do the 👍 or 👎 on the 
> @MaslowCommunityGardenRobot comment. I know that's tough because you mostly 
> read by email, but I am note sure of another solution

I didn't have that option while writing the comment, but after posting the 
comment I then had the option of adding it. (which is why I edited my comment)

David Lang

**Comment by davidelang** [comment]
@BarbourSmith please modify the robot to say that you have to vote on the robot's comment, not in a separate comment.

**Comment by BarbourSmith** [comment]
@dlang you got it. How should I reword the message?

**Comment by davidelang** [comment]
re-reading it, I see it does say "this comment", but I (and probably others) have missed that before now.

can you make that bold, and/or add a note at the end that up/down votes on other comments do not affect this?

I don't know if there's any way to show who voted up/down, that may help

**Comment by BarbourSmith** [comment]
I'm on it!

**Pull request closed without merging**
